-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SEQUENCE "public"."note_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "thread" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "thread_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"content" text,
	"username" text,
	"title" text
);
--> statement-breakpoint
ALTER TABLE "thread" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "note" (
	"id" bigint PRIMARY KEY DEFAULT nextval('note_id_seq'::regclass) NOT NULL,
	"note" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

*/